#!/bin/bash
# Build Pounce.app in this directory. The single source of truth for the
# compile + bundle assembly — called by BOTH the Nix derivation (default.nix)
# and the Homebrew formula (nebelhaus/homebrew-tap), so packagers never drift.
#
# Inputs:
#   POUNCE_VERSION                     stamped into the binary and Info.plist
#                                      (defaults to "dev")
#   Palette+nebelung.generated.swift   must exist next to this script. Nix
#                                      renders it from the nebelung flake input;
#                                      release tarballs ship it pre-rendered.
set -euo pipefail
cd "$(dirname "$0")"

VERSION="${POUNCE_VERSION:-dev}"

if [ ! -f "Palette+nebelung.generated.swift" ]; then
  echo "build.sh: Palette+nebelung.generated.swift is missing." >&2
  echo "  via nix:  nix build .#pounce  (the derivation renders it)" >&2
  echo "  by hand:  nix eval --raw .#packages.aarch64-darwin.pounce.paletteSwift \\" >&2
  echo "              > pkgs/pounce/Palette+nebelung.generated.swift" >&2
  exit 1
fi

cat > Version.generated.swift <<EOF
// AUTO-GENERATED by build.sh — do not edit or commit.
let pounceVersion = "$VERSION"
EOF

mkdir -p Pounce.app/Contents/MacOS Pounce.app/Contents/Resources

# Use xcrun to invoke the system's Swift compiler (from Xcode CLT) — avoids
# building the entire Swift toolchain. All sources compile as a single module,
# so the file split needs no headers or access-level changes.
/usr/bin/xcrun swiftc -parse-as-library -o Pounce.app/Contents/MacOS/pounce \
  *.swift \
  -framework SwiftUI \
  -framework AppKit \
  -framework ApplicationServices \
  -framework AVFoundation \
  -O

cp Info.plist Pounce.app/Contents/
/usr/bin/plutil -replace CFBundleShortVersionString -string "$VERSION" Pounce.app/Contents/Info.plist
/usr/bin/plutil -replace CFBundleVersion -string "$VERSION" Pounce.app/Contents/Info.plist

# Bundle the emoji dataset (read at runtime via Bundle.main).
cp emoji.json Pounce.app/Contents/Resources/
