import AppKit
import CoreGraphics
import ApplicationServices

// MARK: - Pasteboard

enum Pasteboard {
    // Put a file on the clipboard with BOTH a file-URL flavor (⌘V in Finder
    // pastes the file) and image flavors (⌘V in Slack/Notion pastes the picture)
    // on a single pasteboard item, so one copy serves both paste targets.
    static func copyFile(_ url: URL) {
        let pb = NSPasteboard.general
        pb.clearContents()
        let item = NSPasteboardItem()
        item.setString(url.absoluteString, forType: .fileURL)
        if let img = NSImage(contentsOf: url), let tiff = img.tiffRepresentation {
            item.setData(tiff, forType: .tiff)
            if let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
                item.setData(png, forType: .png)
            }
        }
        pb.writeObjects([item])
    }
}

// MARK: - Auto-paste

// Synthesizes a ⌘V keystroke into whatever app is frontmost. Requires the
// process to hold an Accessibility grant (CGEvent posting is gated by TCC);
// callers must check AXIsProcessTrusted() first.
enum Paste {
    private static let kVK_ANSI_V: CGKeyCode = 0x09

    static func sendCommandV() {
        let src = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: src, virtualKey: kVK_ANSI_V, keyDown: true)
        let up = CGEvent(keyboardEventSource: src, virtualKey: kVK_ANSI_V, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}

// One-time nudge when auto-paste is enabled but the daemon isn't trusted yet:
// fire the system Accessibility prompt (which deep-links to the right Settings
// pane), guarded by a marker so it never nags on every paste.
enum AccessibilityHint {
    private static var marker: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/state/pounce/.autopaste-prompted")
    }

    static func promptOnce() {
        let m = marker
        if FileManager.default.fileExists(atPath: m.path) { return }
        try? FileManager.default.createDirectory(at: m.deletingLastPathComponent(),
                                                 withIntermediateDirectories: true)
        FileManager.default.createFile(atPath: m.path, contents: nil)
        let opts = [kAXTrustedCheckOptionPrompt.takeUnretainedValue(): true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(opts)
    }
}

// MARK: - Clipboard History

enum ClipKind: String, Codable { case text, image }

struct ClipEntry: Codable, Identifiable {
    let id: String          // uuid; also the blob filename stem
    let kind: ClipKind
    let ts: Double          // unix time captured
    let appName: String?    // frontmost app at copy time
    let bundleId: String?
    let preview: String     // one-line text snippet, or "1920 × 1080" for images
    let hash: String        // content hash, for dedup
    var width: Int?
    var height: Int?
}

// Records pasteboard history into ~/.local/share/pounce/clipboard and serves it
// to the picker. Lives inside the long-running daemon, polling changeCount —
// NSPasteboard has no change notification. Reading/writing the pasteboard needs
// no special permissions.
final class ClipboardStore {
    static let shared = ClipboardStore()

    private let dir: URL
    private let blobs: URL
    private let indexURL: URL
    private let queue = DispatchQueue(label: "pounce.clipboard")
    private var entriesCache: [ClipEntry] = []
    private var lastChangeCount: Int

    // de-facto nspasteboard.org markers that mean "don't record me".
    private static let skipTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    private init() {
        dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/share/pounce/clipboard")
        blobs = dir.appendingPathComponent("blobs")
        indexURL = dir.appendingPathComponent("index.json")
        lastChangeCount = NSPasteboard.general.changeCount   // ignore whatever's already there
        try? FileManager.default.createDirectory(at: blobs, withIntermediateDirectories: true)
        load()
    }

    // MARK: Public

    func entries() -> [ClipEntry] { queue.sync { entriesCache } }

    func text(for entry: ClipEntry) -> String {
        (try? String(contentsOf: blobURL(entry, ext: "txt"), encoding: .utf8)) ?? entry.preview
    }

    func image(for entry: ClipEntry) -> NSImage? {
        NSImage(contentsOf: blobURL(entry, ext: "png"))
    }

    // Put the entry back on the system clipboard. We bump lastChangeCount past
    // our own write so the poller doesn't re-record it.
    func restore(_ entry: ClipEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch entry.kind {
        case .text: pb.setString(text(for: entry), forType: .string)
        case .image: if let img = image(for: entry) { pb.writeObjects([img]) }
        }
        lastChangeCount = pb.changeCount
    }

    // Called on a timer from the daemon.
    func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        capture(from: pb)
    }

    // MARK: Capture

    private func capture(from pb: NSPasteboard) {
        let types = Set(pb.types ?? [])
        if !Self.skipTypes.allSatisfy({ !types.contains($0) }) { return }   // concealed/transient

        let settings = Settings.load().clipboard
        let front = NSWorkspace.shared.frontmostApplication
        let bundleId = front?.bundleIdentifier
        if let b = bundleId, settings.blacklistBundleIds.contains(b) { return }
        let appName = front?.localizedName

        // Prefer non-empty text; otherwise an image.
        if let s = pb.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            add(makeText(s, appName: appName, bundleId: bundleId), cap: settings.maxEntries)
        } else if let img = NSImage(pasteboard: pb),
                  let png = img.pngData() {
            add(makeImage(png, image: img, appName: appName, bundleId: bundleId),
                cap: settings.maxEntries)
        }
    }

    private func makeText(_ s: String, appName: String?, bundleId: String?) -> (ClipEntry, Data) {
        let data = Data(s.utf8)
        let snippet = s.trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ")
        let preview = String(snippet.prefix(140))
        let entry = ClipEntry(id: UUID().uuidString, kind: .text, ts: Date().timeIntervalSince1970,
                              appName: appName, bundleId: bundleId, preview: preview,
                              hash: Self.fnv1a(data), width: nil, height: nil)
        return (entry, data)
    }

    private func makeImage(_ png: Data, image: NSImage, appName: String?, bundleId: String?) -> (ClipEntry, Data) {
        let w = Int(image.size.width), h = Int(image.size.height)
        let entry = ClipEntry(id: UUID().uuidString, kind: .image, ts: Date().timeIntervalSince1970,
                              appName: appName, bundleId: bundleId, preview: "\(w) × \(h)",
                              hash: Self.fnv1a(png), width: w, height: h)
        return (entry, png)
    }

    private func add(_ made: (ClipEntry, Data), cap: Int) {
        let (entry, data) = made
        queue.sync {
            // Dedup against the most recent entry.
            if entriesCache.first?.hash == entry.hash { return }
            let ext = entry.kind == .text ? "txt" : "png"
            try? data.write(to: blobURL(entry, ext: ext), options: .atomic)
            entriesCache.insert(entry, at: 0)
            while entriesCache.count > max(cap, 1) {
                let dropped = entriesCache.removeLast()
                try? FileManager.default.removeItem(at: blobURL(dropped, ext: dropped.kind == .text ? "txt" : "png"))
            }
            save()
        }
    }

    // MARK: Persistence

    private func blobURL(_ entry: ClipEntry, ext: String) -> URL {
        blobs.appendingPathComponent("\(entry.id).\(ext)")
    }

    private func load() {
        guard let data = try? Data(contentsOf: indexURL),
              let decoded = try? JSONDecoder().decode([ClipEntry].self, from: data) else { return }
        entriesCache = decoded
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(entriesCache) else { return }
        try? data.write(to: indexURL, options: .atomic)
    }

    // Stable 64-bit FNV-1a hash (NOT Swift's per-run hashValue) so dedup works
    // across daemon restarts.
    private static func fnv1a(_ data: Data) -> String {
        var h: UInt64 = 0xcbf29ce484222325
        for b in data { h = (h ^ UInt64(b)) &* 0x100000001b3 }
        return String(h, radix: 16)
    }
}

extension NSImage {
    // PNG encoding of the image's bitmap representation.
    func pngData() -> Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
